--
-- PostgreSQL database dump
--

\restrict fMHM8LjH0vLXLTxTFGTI7dAaug3zYTQAQFItNsE9MrL6K5Y3pGJdkQVSrc3V89h

-- Dumped from database version 17.7 (Postgres.app)
-- Dumped by pg_dump version 17.7 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attendance_leave_attendancerecord; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.attendance_leave_attendancerecord (
    id bigint NOT NULL,
    date date NOT NULL,
    check_in time without time zone,
    check_out time without time zone,
    status character varying(20) NOT NULL,
    work_hours numeric(4,2) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.attendance_leave_attendancerecord OWNER TO hrms_user;

--
-- Name: attendance_leave_attendancerecord_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.attendance_leave_attendancerecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_leave_attendancerecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO hrms_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO hrms_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO hrms_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO hrms_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO hrms_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO hrms_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_auditlog; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.authentication_auditlog (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    resource_type character varying(100) NOT NULL,
    resource_id integer,
    details jsonb NOT NULL,
    ip_address inet,
    "timestamp" timestamp with time zone NOT NULL,
    actor_id integer,
    target_user_id integer
);


ALTER TABLE public.authentication_auditlog OWNER TO hrms_user;

--
-- Name: authentication_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.authentication_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_roleassignment; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.authentication_roleassignment (
    id bigint NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    is_active boolean NOT NULL,
    notes text NOT NULL,
    assigned_by_id integer,
    role_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authentication_roleassignment OWNER TO hrms_user;

--
-- Name: authentication_roleassignment_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.authentication_roleassignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_roleassignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_userpreferences; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.authentication_userpreferences (
    id bigint NOT NULL,
    email_notifications boolean NOT NULL,
    sms_notifications boolean NOT NULL,
    push_notifications boolean NOT NULL,
    theme character varying(20) NOT NULL,
    language character varying(10) NOT NULL,
    timezone character varying(50) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authentication_userpreferences OWNER TO hrms_user;

--
-- Name: authentication_userpreferences_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.authentication_userpreferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_userpreferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_userprofile; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.authentication_userprofile (
    id bigint NOT NULL,
    department character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    employee_id bigint,
    user_id integer NOT NULL,
    password_changed boolean NOT NULL
);


ALTER TABLE public.authentication_userprofile OWNER TO hrms_user;

--
-- Name: authentication_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.authentication_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO hrms_user;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO hrms_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO hrms_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO hrms_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO hrms_user;

--
-- Name: employee_management_employee; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.employee_management_employee (
    id bigint NOT NULL,
    "firstName" character varying(100) NOT NULL,
    "lastName" character varying(100) NOT NULL,
    "employeeId" character varying(20) NOT NULL,
    "personalEmail" character varying(100) NOT NULL,
    "mobileNumber" character varying(15) NOT NULL,
    "joiningDate" date NOT NULL,
    department character varying(100) NOT NULL,
    designation character varying(100) NOT NULL,
    "emergencyContactEmail" character varying(100) NOT NULL,
    "emergencyContactName" character varying(200) NOT NULL,
    "emergencyContactPhone" character varying(20) NOT NULL,
    "emergencyContactRelationship" character varying(100) NOT NULL,
    "employmentStatus" character varying(50) NOT NULL,
    "officeLocation" character varying(200) NOT NULL,
    "preferredName" character varying(100) NOT NULL,
    "profilePhoto" character varying(100),
    "reportingManager_id" bigint,
    "schoolFaculty" character varying(200) NOT NULL,
    "workEmail" character varying(100),
    "workPhone" character varying(20) NOT NULL
);


ALTER TABLE public.employee_management_employee OWNER TO hrms_user;

--
-- Name: employee_management_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.employee_management_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_management_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_management_employeedocument; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.employee_management_employeedocument (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    category character varying(50) NOT NULL,
    file character varying(100) NOT NULL,
    file_type character varying(50) NOT NULL,
    file_size integer NOT NULL,
    upload_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    employee_id bigint NOT NULL,
    uploaded_by_id integer
);


ALTER TABLE public.employee_management_employeedocument OWNER TO hrms_user;

--
-- Name: employee_management_employeedocument_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.employee_management_employeedocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_management_employeedocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_management_holiday; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.leave_management_holiday (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    date date NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.leave_management_holiday OWNER TO hrms_user;

--
-- Name: leave_management_holiday_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.leave_management_holiday ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_management_holiday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_management_leavebalance; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.leave_management_leavebalance (
    id bigint NOT NULL,
    leave_type character varying(50) NOT NULL,
    total integer NOT NULL,
    used integer NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.leave_management_leavebalance OWNER TO hrms_user;

--
-- Name: leave_management_leavebalance_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.leave_management_leavebalance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_management_leavebalance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_management_leaverequest; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.leave_management_leaverequest (
    id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    leave_type character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    reason text NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.leave_management_leaverequest OWNER TO hrms_user;

--
-- Name: leave_management_leaverequest_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.leave_management_leaverequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_management_leaverequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: performance_management_achievement; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.performance_management_achievement (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    awarded_by_id integer,
    employee_id bigint NOT NULL
);


ALTER TABLE public.performance_management_achievement OWNER TO hrms_user;

--
-- Name: performance_management_achievement_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.performance_management_achievement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performance_management_achievement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: performance_management_appraisal; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.performance_management_appraisal (
    id bigint NOT NULL,
    rating numeric(3,1) NOT NULL,
    date date NOT NULL,
    comments text NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    employee_id bigint NOT NULL,
    reviewer_id integer
);


ALTER TABLE public.performance_management_appraisal OWNER TO hrms_user;

--
-- Name: performance_management_appraisal_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.performance_management_appraisal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performance_management_appraisal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: performance_management_goal; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.performance_management_goal (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    target_date date NOT NULL,
    completion_percentage integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.performance_management_goal OWNER TO hrms_user;

--
-- Name: performance_management_goal_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.performance_management_goal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performance_management_goal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: performance_management_training; Type: TABLE; Schema: public; Owner: hrms_user
--

CREATE TABLE public.performance_management_training (
    id bigint NOT NULL,
    course_name character varying(255) NOT NULL,
    description text NOT NULL,
    completion_date date NOT NULL,
    certificate_issued boolean NOT NULL,
    certificate_url character varying(200),
    provider character varying(255) NOT NULL,
    duration_hours integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.performance_management_training OWNER TO hrms_user;

--
-- Name: performance_management_training_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_user
--

ALTER TABLE public.performance_management_training ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performance_management_training_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: attendance_leave_attendancerecord; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.attendance_leave_attendancerecord (id, date, check_in, check_out, status, work_hours, notes, created_at, updated_at, employee_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.auth_group (id, name) FROM stdin;
1	Super Admin
2	HR Manager
4	Employee
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
103	1	28
104	1	25
105	1	26
106	1	27
107	1	45
108	1	47
109	1	32
110	1	29
111	1	30
112	1	31
113	1	60
114	1	62
115	1	59
116	1	56
117	1	57
118	1	51
119	2	28
120	2	25
121	2	26
122	2	27
123	2	45
124	2	47
125	2	32
126	2	29
127	2	30
128	2	60
129	2	62
130	2	59
131	4	28
132	4	32
133	4	29
134	4	63
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add employee	7	add_employee
26	Can change employee	7	change_employee
27	Can delete employee	7	delete_employee
28	Can view employee	7	view_employee
29	Can add leave request	8	add_leaverequest
30	Can change leave request	8	change_leaverequest
31	Can delete leave request	8	delete_leaverequest
32	Can view leave request	8	view_leaverequest
33	Can add Token	9	add_token
34	Can change Token	9	change_token
35	Can delete Token	9	delete_token
36	Can view Token	9	view_token
37	Can add Token	10	add_tokenproxy
38	Can change Token	10	change_tokenproxy
39	Can delete Token	10	delete_tokenproxy
40	Can view Token	10	view_tokenproxy
41	Can add profile	11	add_profile
42	Can change profile	11	change_profile
43	Can delete profile	11	delete_profile
44	Can view profile	11	view_profile
45	Can view all employees	7	view_all_employees
46	Can view department employees	7	view_department_employees
47	Can manage employees	7	manage_employees
48	Can add Audit Log	12	add_auditlog
49	Can change Audit Log	12	change_auditlog
50	Can delete Audit Log	12	delete_auditlog
51	Can view Audit Log	12	view_auditlog
52	Can add Role Assignment	13	add_roleassignment
53	Can change Role Assignment	13	change_roleassignment
54	Can delete Role Assignment	13	delete_roleassignment
55	Can view Role Assignment	13	view_roleassignment
56	Can add User Profile	14	add_userprofile
57	Can change User Profile	14	change_userprofile
58	Can delete User Profile	14	delete_userprofile
59	Can view User Profile	14	view_userprofile
60	Can view all leave requests	8	view_all_leaves
61	Can view department leave requests	8	view_department_leaves
62	Can approve leave requests	8	approve_leaves
63	Can manage own leave requests	8	manage_own_leaves
64	Can add Employee Document	15	add_employeedocument
65	Can change Employee Document	15	change_employeedocument
66	Can delete Employee Document	15	delete_employeedocument
67	Can view Employee Document	15	view_employeedocument
68	Can add User Preferences	16	add_userpreferences
69	Can change User Preferences	16	change_userpreferences
70	Can delete User Preferences	16	delete_userpreferences
71	Can view User Preferences	16	view_userpreferences
72	Can add Achievement	17	add_achievement
73	Can change Achievement	17	change_achievement
74	Can delete Achievement	17	delete_achievement
75	Can view Achievement	17	view_achievement
76	Can add Appraisal	18	add_appraisal
77	Can change Appraisal	18	change_appraisal
78	Can delete Appraisal	18	delete_appraisal
79	Can view Appraisal	18	view_appraisal
80	Can add Training	19	add_training
81	Can change Training	19	change_training
82	Can delete Training	19	delete_training
83	Can view Training	19	view_training
84	Can add Goal	20	add_goal
85	Can change Goal	20	change_goal
86	Can delete Goal	20	delete_goal
87	Can view Goal	20	view_goal
88	Can add Attendance Record	21	add_attendancerecord
89	Can change Attendance Record	21	change_attendancerecord
90	Can delete Attendance Record	21	delete_attendancerecord
91	Can view Attendance Record	21	view_attendancerecord
92	Can add Holiday	22	add_holiday
93	Can change Holiday	22	change_holiday
94	Can delete Holiday	22	delete_holiday
95	Can view Holiday	22	view_holiday
96	Can add Leave Balance	23	add_leavebalance
97	Can change Leave Balance	23	change_leavebalance
98	Can delete Leave Balance	23	delete_leavebalance
99	Can view Leave Balance	23	view_leavebalance
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
14	pbkdf2_sha256$600000$ZiBvDfEto7ZczuDKygOcfp$tsqai33CdgrT9qzOz0OwPPge7Yyc9mxBSGsoVkKAUSs=	\N	t	superadmin	Super	Admin	superadmin@university.edu	t	t	2025-11-16 08:22:33.806508+00
17	pbkdf2_sha256$600000$fw3cB9gi3jFgRLvIiCtQwi$yVbtIN+W5DLsrEeUz3T/m2iLXdTl5iIL1zyxB7dxegQ=	\N	f	ishitaparkar04@gmail.com	Ishita	Parkar	ishitaparkar04@gmail.com	f	t	2025-11-17 10:03:57.837965+00
15	pbkdf2_sha256$600000$RUZr8I5yFhxG4EB6GZPx87$SCuAgc5+rKKsvOe5MTu63BcvuHm8GsTra9UkPKzxc7g=	\N	f	hrmanager	HR	Manager	hrmanager@university.edu	t	t	2025-11-16 08:22:33.95884+00
19	!MaI2d0C54FEig5cOys5fAK4yGbJMVrY1iZOPSFKx	\N	f	pruthajadhav82@gmail.com	Prutha	Jadhav	pruthajadhav82@gmail.com	f	t	2025-11-17 18:59:27.23625+00
16	pbkdf2_sha256$600000$dn87eiJZbBCQGaH2Edoyol$8bBz4xo852TTFCCcXbeP5T3pCE1Ve3/1LyvED5pbmxQ=	\N	f	employee	Test	Employee	employee@university.edu	f	t	2025-11-16 08:22:34.101722+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
19	14	1
20	15	2
21	16	4
22	17	4
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authentication_auditlog; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.authentication_auditlog (id, action, resource_type, resource_id, details, ip_address, "timestamp", actor_id, target_user_id) FROM stdin;
3	ACCESS_DENIED	Employee	1	{"test": "denied"}	\N	2025-11-15 22:04:40.769494+00	\N	\N
5	ACCESS_DENIED	Employee	1	{"test": "denied"}	\N	2025-11-15 22:05:02.587747+00	\N	\N
1	ROLE_ASSIGNED	Role	1	{"test": "data"}	\N	2025-11-15 22:04:11.838021+00	\N	\N
2	ROLE_ASSIGNED	Role	1	{"test": "data"}	\N	2025-11-15 22:04:40.768739+00	\N	\N
4	ROLE_ASSIGNED	Role	1	{"test": "data"}	\N	2025-11-15 22:05:02.586213+00	\N	\N
6	ACCESS_DENIED	RoleListCreateAPIView	\N	{"timestamp": "2025-11-17T08:13:00.197423+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/roles/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:13:00.197912+00	16	\N
7	ACCESS_DENIED	UserListAPIView	\N	{"timestamp": "2025-11-17T08:13:00.198156+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/users/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:13:00.198286+00	16	\N
8	ACCESS_DENIED	AuditLogListAPIView	\N	{"timestamp": "2025-11-17T08:13:06.555484+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/audit-logs/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:13:06.555735+00	16	\N
9	ACCESS_DENIED	UserListAPIView	\N	{"timestamp": "2025-11-17T08:19:19.569543+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/users/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:19:19.569733+00	16	\N
10	ACCESS_DENIED	RoleListCreateAPIView	\N	{"timestamp": "2025-11-17T08:19:19.569887+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/roles/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:19:19.57002+00	16	\N
11	ACCESS_DENIED	AuditLogListAPIView	\N	{"timestamp": "2025-11-17T08:19:24.162114+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/audit-logs/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:19:24.16247+00	16	\N
12	ACCESS_DENIED	UserListAPIView	\N	{"timestamp": "2025-11-17T08:19:39.264203+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/users/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:19:39.264512+00	16	\N
13	ACCESS_DENIED	RoleListCreateAPIView	\N	{"timestamp": "2025-11-17T08:19:39.264749+00:00", "user_roles": ["Employee"], "request_path": "/api/auth/roles/", "request_method": "GET", "required_roles": ["Super Admin"], "required_permission": "role:Super Admin"}	127.0.0.1	2025-11-17 08:19:39.264927+00	16	\N
\.


--
-- Data for Name: authentication_roleassignment; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.authentication_roleassignment (id, assigned_at, expires_at, is_active, notes, assigned_by_id, role_id, user_id) FROM stdin;
\.


--
-- Data for Name: authentication_userpreferences; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.authentication_userpreferences (id, email_notifications, sms_notifications, push_notifications, theme, language, timezone, updated_at, user_id) FROM stdin;
2	f	f	f	light	en	UTC	2025-11-18 14:46:44.006888+00	16
3	t	f	t	system	en	UTC	2025-11-18 14:56:28.732167+00	15
6	t	f	t	system	en	UTC	2025-11-18 16:09:01.765624+00	14
5	t	f	t	light	en	UTC	2025-11-18 17:49:31.023899+00	17
\.


--
-- Data for Name: authentication_userprofile; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.authentication_userprofile (id, department, phone_number, created_at, updated_at, employee_id, user_id, password_changed) FROM stdin;
14	Administration		2025-11-16 08:22:33.954392+00	2025-11-16 08:22:33.954399+00	13	14	t
15	Human Resources		2025-11-16 08:22:34.099623+00	2025-11-16 08:22:34.099627+00	14	15	t
16	General		2025-11-16 08:22:34.245028+00	2025-11-16 08:22:34.245034+00	\N	16	t
17			2025-11-17 19:53:34.758027+00	2025-11-18 14:52:06.58211+00	1	17	t
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
20f6e84a3458c70d7781395acfc61d46c867a4c3	2025-11-16 10:41:56.633336+00	14
f4b044da9557a18a2dc727db6327ff296fe869ba	2025-11-16 10:46:39.326452+00	15
6cfb9435434b288366218b9933000331c85d5d76	2025-11-16 11:18:10.434055+00	16
fda576fb9aeb5024d995ff916b6ad6163b7b0c5e	2025-11-17 19:47:56.302534+00	17
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	employee_management	employee
8	leave_management	leaverequest
9	authtoken	token
10	authtoken	tokenproxy
11	authentication	profile
12	authentication	auditlog
13	authentication	roleassignment
14	authentication	userprofile
15	employee_management	employeedocument
16	authentication	userpreferences
17	performance_management	achievement
18	performance_management	appraisal
19	performance_management	training
20	performance_management	goal
21	attendance_leave	attendancerecord
22	leave_management	holiday
23	leave_management	leavebalance
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-25 15:30:42.945946+00
2	auth	0001_initial	2025-10-25 15:30:42.961416+00
3	admin	0001_initial	2025-10-25 15:30:42.966523+00
4	admin	0002_logentry_remove_auto_add	2025-10-25 15:30:42.968845+00
5	admin	0003_logentry_add_action_flag_choices	2025-10-25 15:30:42.972304+00
6	contenttypes	0002_remove_content_type_name	2025-10-25 15:30:42.977213+00
7	auth	0002_alter_permission_name_max_length	2025-10-25 15:30:42.97963+00
8	auth	0003_alter_user_email_max_length	2025-10-25 15:30:42.982606+00
9	auth	0004_alter_user_username_opts	2025-10-25 15:30:42.98555+00
10	auth	0005_alter_user_last_login_null	2025-10-25 15:30:42.988824+00
11	auth	0006_require_contenttypes_0002	2025-10-25 15:30:42.989999+00
12	auth	0007_alter_validators_add_error_messages	2025-10-25 15:30:42.992862+00
13	auth	0008_alter_user_username_max_length	2025-10-25 15:30:42.998584+00
14	auth	0009_alter_user_last_name_max_length	2025-10-25 15:30:43.001184+00
15	auth	0010_alter_group_name_max_length	2025-10-25 15:30:43.004739+00
16	auth	0011_update_proxy_permissions	2025-10-25 15:30:43.007246+00
17	auth	0012_alter_user_first_name_max_length	2025-10-25 15:30:43.010216+00
18	employee_management	0001_initial	2025-10-25 15:30:43.017548+00
19	leave_management	0001_initial	2025-10-25 15:30:43.023665+00
20	sessions	0001_initial	2025-10-25 15:30:43.028699+00
21	authtoken	0001_initial	2025-10-25 15:53:02.859896+00
22	authtoken	0002_auto_20160226_1747	2025-10-25 15:53:02.868592+00
23	authtoken	0003_tokenproxy	2025-10-25 15:53:02.869943+00
24	authtoken	0004_alter_tokenproxy_options	2025-10-25 15:53:02.871758+00
25	authentication	0001_initial	2025-10-27 07:37:01.385879+00
26	employee_management	0002_alter_employee_options	2025-11-15 21:13:00.592251+00
27	authentication	0002_auditlog_roleassignment_userprofile_delete_profile	2025-11-15 21:13:00.619978+00
28	leave_management	0002_alter_leaverequest_options	2025-11-15 21:13:00.621527+00
29	authentication	0003_populate_user_profiles	2025-11-15 22:19:04.17096+00
30	authentication	0004_userprofile_password_changed	2025-11-17 08:46:55.51853+00
31	employee_management	0003_employeedocument	2025-11-18 10:34:57.626305+00
32	authentication	0005_userpreferences	2025-11-18 10:44:10.852622+00
33	performance_management	0001_initial	2025-11-18 10:59:02.435512+00
34	attendance_leave	0001_initial	2025-11-18 11:04:52.15464+00
35	leave_management	0003_holiday_leavebalance	2025-11-18 11:08:58.66492+00
36	employee_management	0004_employee_emergencycontactemail_and_more	2025-11-18 16:36:09.64672+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
63z5yp65wotyc4kgmh2yf1uzbnt9drsk	e30:1vDIDh:5QNvPkvGam2EicJgtefenocNr2VlktGG2cPaSUAFob0	2025-11-10 08:04:49.147579+00
pumbjbrv2c5ts9zpul8oc6bzwda2sldl	e30:1vDIH1:PZXGWt9o0_GU59hougdS3clPR46vJnEfjCbgoriB7Co	2025-11-10 08:08:15.375924+00
\.


--
-- Data for Name: employee_management_employee; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.employee_management_employee (id, "firstName", "lastName", "employeeId", "personalEmail", "mobileNumber", "joiningDate", department, designation, "emergencyContactEmail", "emergencyContactName", "emergencyContactPhone", "emergencyContactRelationship", "employmentStatus", "officeLocation", "preferredName", "profilePhoto", "reportingManager_id", "schoolFaculty", "workEmail", "workPhone") FROM stdin;
2	Prutha	Jadhav	002	pruthajadhav82@gmail.com	9326662460	2025-09-11	Faculty of Arts & Commerce	Lecturer	emergency.prutha@email.com	Emergency Contact for Prutha	+1-555-9999	Spouse	Active	Building A, Floor 3	Prutha		\N	School of Engineering	prutha.jadhav@company.com	+1-555-0100
4	Yash	Adhau	003	yashadhau2@gmail.com	8729838092	2025-08-28	Faculty of Engineering	Professor	emergency.yash@email.com	Emergency Contact for Yash	+1-555-9999	Spouse	Active	Building A, Floor 3	Yash		\N	School of Engineering	yash.adhau@company.com	+1-555-0100
3	Bhavya	Sharma	004	bhavyasharma05@gmail.com	987654345678	2025-10-17	Administration	Professor	emergency.bhavya@email.com	Emergency Contact for Bhavya	+1-555-9999	Spouse	Active	Building A, Floor 3	Bhavya		\N	School of Engineering	bhavya.sharma@company.com	+1-555-0100
5	Viraj	Sawant	005	virajsawant@123gmail.com	76545678767	2025-09-10	Faculty of Design	Design Mentor	emergency.viraj@email.com	Emergency Contact for Viraj	+1-555-9999	Spouse	Active	Building A, Floor 3	Viraj		\N	School of Engineering	viraj.sawant@company.com	+1-555-0100
7	prasad	sawant	007	prasaddekhmukh25@gmail.com	9221333969	2025-10-01	Faculty of Management	Professor	emergency.prasad@email.com	Emergency Contact for prasad	+1-555-9999	Spouse	Active	Building A, Floor 3	prasad		\N	School of Engineering	prasad.sawant@company.com	+1-555-0100
8	Sarah	Johnson	EMP0009	hr.manager@university.edu	+1-555-1009	2023-01-01	Human Resources	HR Manager	emergency.sarah@email.com	Emergency Contact for Sarah	+1-555-9999	Spouse	Active	Building A, Floor 3	Sarah		\N	School of Engineering	sarah.johnson@company.com	+1-555-0100
9	Michael	Chen	EMP0010	head.cs@university.edu	+1-555-1010	2023-01-01	Computer Science	Department Head	emergency.michael@email.com	Emergency Contact for Michael	+1-555-9999	Spouse	Active	Building A, Floor 3	Michael		\N	School of Engineering	michael.chen@company.com	+1-555-0100
10	Emily	Rodriguez	EMP0011	head.math@university.edu	+1-555-1011	2023-01-01	Mathematics	Department Head	emergency.emily@email.com	Emergency Contact for Emily	+1-555-9999	Spouse	Active	Building A, Floor 3	Emily		\N	School of Engineering	emily.rodriguez@company.com	+1-555-0100
11	John	Doe	EMP0012	john.doe@university.edu	+1-555-1012	2023-01-01	Computer Science	Assistant Professor	emergency.john@email.com	Emergency Contact for John	+1-555-9999	Spouse	Active	Building A, Floor 3	John		\N	School of Engineering	john.doe@company.com	+1-555-0100
12	Jane	Smith	EMP0013	jane.smith@university.edu	+1-555-1013	2023-01-01	Mathematics	Lecturer	emergency.jane@email.com	Emergency Contact for Jane	+1-555-9999	Spouse	Active	Building A, Floor 3	Jane		\N	School of Engineering	jane.smith@company.com	+1-555-0100
13	Super	Admin	SUP0014	superadmin@university.edu	+1-555-1014	2024-01-01	Administration	System Administrator	emergency.super@email.com	Emergency Contact for Super	+1-555-9999	Spouse	Active	Building A, Floor 3	Super		\N	School of Engineering	super.admin@company.com	+1-555-0100
14	HR	Manager	HRM0015	hrmanager@university.edu	+1-555-1015	2024-01-01	Human Resources	HR Manager	emergency.hr@email.com	Emergency Contact for HR	+1-555-9999	Spouse	Active	Building A, Floor 3	HR		\N	School of Engineering	hr.manager@company.com	+1-555-0100
1	Ishita	Parkar	001	ishitaparkar04@gmail.com	9326662460	2025-08-17	Faculty of Engineering	Professor	john.parkar@email.com	John Parkar	+1-555-9876	Spouse	Active	Building A, Floor 3	Ishi		\N	School of Engineering	ishita.parkar@company.com	+1-555-0123
\.


--
-- Data for Name: employee_management_employeedocument; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.employee_management_employeedocument (id, name, category, file, file_type, file_size, upload_date, status, employee_id, uploaded_by_id) FROM stdin;
\.


--
-- Data for Name: leave_management_holiday; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.leave_management_holiday (id, name, date, description) FROM stdin;
1	New Year's Day	2025-01-01	New Year celebration
2	Independence Day	2026-07-04	National holiday
3	Christmas	2025-12-25	Christmas celebration
4	Thanksgiving	2026-01-17	Thanksgiving holiday
\.


--
-- Data for Name: leave_management_leavebalance; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.leave_management_leavebalance (id, leave_type, total, used, employee_id) FROM stdin;
1	Casual	10	0	1
2	Sick	10	0	1
3	Vacation	15	0	1
4	Casual	10	0	2
5	Sick	10	0	2
6	Vacation	15	0	2
7	Casual	10	0	4
8	Sick	10	0	4
9	Vacation	15	0	4
10	Casual	10	0	3
11	Sick	10	0	3
12	Vacation	15	0	3
13	Casual	10	0	5
14	Sick	10	0	5
15	Vacation	15	0	5
16	Casual	10	0	7
17	Sick	10	0	7
18	Vacation	15	0	7
19	Casual	10	0	8
20	Sick	10	0	8
21	Vacation	15	0	8
22	Casual	10	0	9
23	Sick	10	0	9
24	Vacation	15	0	9
25	Casual	10	0	10
26	Sick	10	0	10
27	Vacation	15	0	10
28	Casual	10	0	11
29	Sick	10	0	11
30	Vacation	15	0	11
31	Casual	10	0	12
32	Sick	10	0	12
33	Vacation	15	0	12
34	Casual	10	0	13
35	Sick	10	0	13
36	Vacation	15	0	13
37	Casual	10	0	14
38	Sick	10	0	14
39	Vacation	15	0	14
\.


--
-- Data for Name: leave_management_leaverequest; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.leave_management_leaverequest (id, start_date, end_date, leave_type, status, reason, employee_id) FROM stdin;
1	2025-10-29	2025-11-06	Casual Leave	Approved		1
2	2025-11-11	2025-11-21	Casual Leave	Pending	International Conference	2
\.


--
-- Data for Name: performance_management_achievement; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.performance_management_achievement (id, title, description, date, created_at, updated_at, awarded_by_id, employee_id) FROM stdin;
\.


--
-- Data for Name: performance_management_appraisal; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.performance_management_appraisal (id, rating, date, comments, period_start, period_end, created_at, updated_at, employee_id, reviewer_id) FROM stdin;
\.


--
-- Data for Name: performance_management_goal; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.performance_management_goal (id, title, description, target_date, completion_percentage, status, created_at, updated_at, employee_id) FROM stdin;
\.


--
-- Data for Name: performance_management_training; Type: TABLE DATA; Schema: public; Owner: hrms_user
--

COPY public.performance_management_training (id, course_name, description, completion_date, certificate_issued, certificate_url, provider, duration_hours, created_at, updated_at, employee_id) FROM stdin;
\.


--
-- Name: attendance_leave_attendancerecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.attendance_leave_attendancerecord_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 4, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 134, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 99, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 22, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 20, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: authentication_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.authentication_auditlog_id_seq', 13, true);


--
-- Name: authentication_roleassignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.authentication_roleassignment_id_seq', 4, true);


--
-- Name: authentication_userpreferences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.authentication_userpreferences_id_seq', 7, true);


--
-- Name: authentication_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.authentication_userprofile_id_seq', 17, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 23, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 36, true);


--
-- Name: employee_management_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.employee_management_employee_id_seq', 15, true);


--
-- Name: employee_management_employeedocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.employee_management_employeedocument_id_seq', 1, false);


--
-- Name: leave_management_holiday_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.leave_management_holiday_id_seq', 4, true);


--
-- Name: leave_management_leavebalance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.leave_management_leavebalance_id_seq', 39, true);


--
-- Name: leave_management_leaverequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.leave_management_leaverequest_id_seq', 2, true);


--
-- Name: performance_management_achievement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.performance_management_achievement_id_seq', 1, false);


--
-- Name: performance_management_appraisal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.performance_management_appraisal_id_seq', 1, false);


--
-- Name: performance_management_goal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.performance_management_goal_id_seq', 1, false);


--
-- Name: performance_management_training_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_user
--

SELECT pg_catalog.setval('public.performance_management_training_id_seq', 1, false);


--
-- Name: attendance_leave_attendancerecord attendance_leave_attenda_employee_id_date_7c241b2d_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.attendance_leave_attendancerecord
    ADD CONSTRAINT attendance_leave_attenda_employee_id_date_7c241b2d_uniq UNIQUE (employee_id, date);


--
-- Name: attendance_leave_attendancerecord attendance_leave_attendancerecord_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.attendance_leave_attendancerecord
    ADD CONSTRAINT attendance_leave_attendancerecord_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authentication_auditlog authentication_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_auditlog
    ADD CONSTRAINT authentication_auditlog_pkey PRIMARY KEY (id);


--
-- Name: authentication_roleassignment authentication_roleassignment_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_roleassignment
    ADD CONSTRAINT authentication_roleassignment_pkey PRIMARY KEY (id);


--
-- Name: authentication_userpreferences authentication_userpreferences_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userpreferences
    ADD CONSTRAINT authentication_userpreferences_pkey PRIMARY KEY (id);


--
-- Name: authentication_userpreferences authentication_userpreferences_user_id_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userpreferences
    ADD CONSTRAINT authentication_userpreferences_user_id_key UNIQUE (user_id);


--
-- Name: authentication_userprofile authentication_userprofile_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userprofile
    ADD CONSTRAINT authentication_userprofile_employee_id_key UNIQUE (employee_id);


--
-- Name: authentication_userprofile authentication_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userprofile
    ADD CONSTRAINT authentication_userprofile_pkey PRIMARY KEY (id);


--
-- Name: authentication_userprofile authentication_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userprofile
    ADD CONSTRAINT authentication_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: employee_management_employee employee_management_employee_employeeId_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employee
    ADD CONSTRAINT "employee_management_employee_employeeId_key" UNIQUE ("employeeId");


--
-- Name: employee_management_employee employee_management_employee_personalEmail_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employee
    ADD CONSTRAINT "employee_management_employee_personalEmail_key" UNIQUE ("personalEmail");


--
-- Name: employee_management_employee employee_management_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employee
    ADD CONSTRAINT employee_management_employee_pkey PRIMARY KEY (id);


--
-- Name: employee_management_employee employee_management_employee_workEmail_key; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employee
    ADD CONSTRAINT "employee_management_employee_workEmail_key" UNIQUE ("workEmail");


--
-- Name: employee_management_employeedocument employee_management_employeedocument_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employeedocument
    ADD CONSTRAINT employee_management_employeedocument_pkey PRIMARY KEY (id);


--
-- Name: leave_management_holiday leave_management_holiday_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.leave_management_holiday
    ADD CONSTRAINT leave_management_holiday_pkey PRIMARY KEY (id);


--
-- Name: leave_management_leavebalance leave_management_leaveba_employee_id_leave_type_6ee55307_uniq; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.leave_management_leavebalance
    ADD CONSTRAINT leave_management_leaveba_employee_id_leave_type_6ee55307_uniq UNIQUE (employee_id, leave_type);


--
-- Name: leave_management_leavebalance leave_management_leavebalance_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.leave_management_leavebalance
    ADD CONSTRAINT leave_management_leavebalance_pkey PRIMARY KEY (id);


--
-- Name: leave_management_leaverequest leave_management_leaverequest_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.leave_management_leaverequest
    ADD CONSTRAINT leave_management_leaverequest_pkey PRIMARY KEY (id);


--
-- Name: performance_management_achievement performance_management_achievement_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_achievement
    ADD CONSTRAINT performance_management_achievement_pkey PRIMARY KEY (id);


--
-- Name: performance_management_appraisal performance_management_appraisal_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_appraisal
    ADD CONSTRAINT performance_management_appraisal_pkey PRIMARY KEY (id);


--
-- Name: performance_management_goal performance_management_goal_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_goal
    ADD CONSTRAINT performance_management_goal_pkey PRIMARY KEY (id);


--
-- Name: performance_management_training performance_management_training_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_training
    ADD CONSTRAINT performance_management_training_pkey PRIMARY KEY (id);


--
-- Name: attendance__date_02aea3_idx; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX attendance__date_02aea3_idx ON public.attendance_leave_attendancerecord USING btree (date);


--
-- Name: attendance__employe_ee9d1b_idx; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX attendance__employe_ee9d1b_idx ON public.attendance_leave_attendancerecord USING btree (employee_id, date);


--
-- Name: attendance_leave_attendancerecord_date_1e814dc6; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX attendance_leave_attendancerecord_date_1e814dc6 ON public.attendance_leave_attendancerecord USING btree (date);


--
-- Name: attendance_leave_attendancerecord_employee_id_d58a98af; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX attendance_leave_attendancerecord_employee_id_d58a98af ON public.attendance_leave_attendancerecord USING btree (employee_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authentication_auditlog_actor_id_6e588a5f; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX authentication_auditlog_actor_id_6e588a5f ON public.authentication_auditlog USING btree (actor_id);


--
-- Name: authentication_auditlog_target_user_id_abe0e6aa; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX authentication_auditlog_target_user_id_abe0e6aa ON public.authentication_auditlog USING btree (target_user_id);


--
-- Name: authentication_roleassignment_assigned_by_id_be1a4301; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX authentication_roleassignment_assigned_by_id_be1a4301 ON public.authentication_roleassignment USING btree (assigned_by_id);


--
-- Name: authentication_roleassignment_role_id_6a530ca1; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX authentication_roleassignment_role_id_6a530ca1 ON public.authentication_roleassignment USING btree (role_id);


--
-- Name: authentication_roleassignment_user_id_868fbab5; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX authentication_roleassignment_user_id_868fbab5 ON public.authentication_roleassignment USING btree (user_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: employee_management_employee_employeeId_eb66e093_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX "employee_management_employee_employeeId_eb66e093_like" ON public.employee_management_employee USING btree ("employeeId" varchar_pattern_ops);


--
-- Name: employee_management_employee_personalEmail_90907dd9_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX "employee_management_employee_personalEmail_90907dd9_like" ON public.employee_management_employee USING btree ("personalEmail" varchar_pattern_ops);


--
-- Name: employee_management_employee_reportingManager_id_f8b865e7; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX "employee_management_employee_reportingManager_id_f8b865e7" ON public.employee_management_employee USING btree ("reportingManager_id");


--
-- Name: employee_management_employee_workEmail_a08d383d_like; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX "employee_management_employee_workEmail_a08d383d_like" ON public.employee_management_employee USING btree ("workEmail" varchar_pattern_ops);


--
-- Name: employee_management_employeedocument_employee_id_bd496a95; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX employee_management_employeedocument_employee_id_bd496a95 ON public.employee_management_employeedocument USING btree (employee_id);


--
-- Name: employee_management_employeedocument_uploaded_by_id_ae65b6df; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX employee_management_employeedocument_uploaded_by_id_ae65b6df ON public.employee_management_employeedocument USING btree (uploaded_by_id);


--
-- Name: leave_management_leavebalance_employee_id_4bddc6b9; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX leave_management_leavebalance_employee_id_4bddc6b9 ON public.leave_management_leavebalance USING btree (employee_id);


--
-- Name: leave_management_leaverequest_employee_id_7af82e84; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX leave_management_leaverequest_employee_id_7af82e84 ON public.leave_management_leaverequest USING btree (employee_id);


--
-- Name: performance_management_achievement_awarded_by_id_2381e7f8; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX performance_management_achievement_awarded_by_id_2381e7f8 ON public.performance_management_achievement USING btree (awarded_by_id);


--
-- Name: performance_management_achievement_employee_id_65b3be1b; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX performance_management_achievement_employee_id_65b3be1b ON public.performance_management_achievement USING btree (employee_id);


--
-- Name: performance_management_appraisal_employee_id_4d648163; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX performance_management_appraisal_employee_id_4d648163 ON public.performance_management_appraisal USING btree (employee_id);


--
-- Name: performance_management_appraisal_reviewer_id_73549a8a; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX performance_management_appraisal_reviewer_id_73549a8a ON public.performance_management_appraisal USING btree (reviewer_id);


--
-- Name: performance_management_goal_employee_id_d7948a7f; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX performance_management_goal_employee_id_d7948a7f ON public.performance_management_goal USING btree (employee_id);


--
-- Name: performance_management_training_employee_id_ea474936; Type: INDEX; Schema: public; Owner: hrms_user
--

CREATE INDEX performance_management_training_employee_id_ea474936 ON public.performance_management_training USING btree (employee_id);


--
-- Name: attendance_leave_attendancerecord attendance_leave_att_employee_id_d58a98af_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.attendance_leave_attendancerecord
    ADD CONSTRAINT attendance_leave_att_employee_id_d58a98af_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_auditlog authentication_auditlog_actor_id_6e588a5f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_auditlog
    ADD CONSTRAINT authentication_auditlog_actor_id_6e588a5f_fk_auth_user_id FOREIGN KEY (actor_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_auditlog authentication_auditlog_target_user_id_abe0e6aa_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_auditlog
    ADD CONSTRAINT authentication_auditlog_target_user_id_abe0e6aa_fk_auth_user_id FOREIGN KEY (target_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_roleassignment authentication_rolea_assigned_by_id_be1a4301_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_roleassignment
    ADD CONSTRAINT authentication_rolea_assigned_by_id_be1a4301_fk_auth_user FOREIGN KEY (assigned_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_roleassignment authentication_roleassignment_role_id_6a530ca1_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_roleassignment
    ADD CONSTRAINT authentication_roleassignment_role_id_6a530ca1_fk_auth_group_id FOREIGN KEY (role_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_roleassignment authentication_roleassignment_user_id_868fbab5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_roleassignment
    ADD CONSTRAINT authentication_roleassignment_user_id_868fbab5_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_userprofile authentication_userp_employee_id_780d491c_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userprofile
    ADD CONSTRAINT authentication_userp_employee_id_780d491c_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_userpreferences authentication_userpreferences_user_id_09630697_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userpreferences
    ADD CONSTRAINT authentication_userpreferences_user_id_09630697_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_userprofile authentication_userprofile_user_id_83547247_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authentication_userprofile
    ADD CONSTRAINT authentication_userprofile_user_id_83547247_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_management_employeedocument employee_management__employee_id_bd496a95_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employeedocument
    ADD CONSTRAINT employee_management__employee_id_bd496a95_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_management_employee employee_management__reportingManager_id_f8b865e7_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employee
    ADD CONSTRAINT "employee_management__reportingManager_id_f8b865e7_fk_employee_" FOREIGN KEY ("reportingManager_id") REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_management_employeedocument employee_management__uploaded_by_id_ae65b6df_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.employee_management_employeedocument
    ADD CONSTRAINT employee_management__uploaded_by_id_ae65b6df_fk_auth_user FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leave_management_leavebalance leave_management_lea_employee_id_4bddc6b9_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.leave_management_leavebalance
    ADD CONSTRAINT leave_management_lea_employee_id_4bddc6b9_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leave_management_leaverequest leave_management_lea_employee_id_7af82e84_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.leave_management_leaverequest
    ADD CONSTRAINT leave_management_lea_employee_id_7af82e84_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: performance_management_achievement performance_manageme_awarded_by_id_2381e7f8_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_achievement
    ADD CONSTRAINT performance_manageme_awarded_by_id_2381e7f8_fk_auth_user FOREIGN KEY (awarded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: performance_management_appraisal performance_manageme_employee_id_4d648163_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_appraisal
    ADD CONSTRAINT performance_manageme_employee_id_4d648163_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: performance_management_achievement performance_manageme_employee_id_65b3be1b_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_achievement
    ADD CONSTRAINT performance_manageme_employee_id_65b3be1b_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: performance_management_goal performance_manageme_employee_id_d7948a7f_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_goal
    ADD CONSTRAINT performance_manageme_employee_id_d7948a7f_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: performance_management_training performance_manageme_employee_id_ea474936_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_training
    ADD CONSTRAINT performance_manageme_employee_id_ea474936_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_management_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: performance_management_appraisal performance_manageme_reviewer_id_73549a8a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: hrms_user
--

ALTER TABLE ONLY public.performance_management_appraisal
    ADD CONSTRAINT performance_manageme_reviewer_id_73549a8a_fk_auth_user FOREIGN KEY (reviewer_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO hrms_user;


--
-- PostgreSQL database dump complete
--

\unrestrict fMHM8LjH0vLXLTxTFGTI7dAaug3zYTQAQFItNsE9MrL6K5Y3pGJdkQVSrc3V89h

